using System.Globalization;
using Content.Client.Atmos.Rotting;
using Content.Client.Message;
using Content.Shared._RMC14.Chemistry.Reagent;
using Content.Shared._RMC14.Marines.Skills;
using Content.Shared._RMC14.Medical.Defibrillator;
using Content.Shared._RMC14.Medical.HUD;
using Content.Shared._RMC14.Medical.HUD.Components;
using Content.Shared._RMC14.Medical.Scanner;
using Content.Shared._RMC14.Medical.Unrevivable;
using Content.Shared._RMC14.Medical.Wounds;
using Content.Shared._RMC14.Xenonids.Parasite;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage;
using Content.Shared.Damage.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.Mobs.Systems;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.Medical.BodyScanner;

[GenerateTypedNameReferences]
public sealed partial class BodyScannerConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entities = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private BodyScannerConsoleBui? _bui;

    private readonly SkillsSystem _skills;
    private readonly SharedWoundsSystem _wounds;
    private readonly RMCUnrevivableSystem _unrevivable;
    private readonly MobStateSystem _mob;
    private readonly RottingSystem _rot;

    private static readonly Dictionary<EntProtoId<SkillDefinitionComponent>, int> BloodPackSkill = new() { ["RMCSkillSurgery"] = 1 };
    private static readonly Dictionary<EntProtoId<SkillDefinitionComponent>, int> DefibSkill = new() { ["RMCSkillMedical"] = 2 };
    private static readonly Dictionary<EntProtoId<SkillDefinitionComponent>, int> LarvaSurgerySkill = new() { ["RMCSkillSurgery"] = 2 };

    public BodyScannerConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _skills = _entities.System<SkillsSystem>();
        _wounds = _entities.System<SharedWoundsSystem>();
        _unrevivable = _entities.System<RMCUnrevivableSystem>();
        _mob = _entities.System<MobStateSystem>();
        _rot = _entities.System<RottingSystem>();

        EjectButton.OnPressed += _ => _bui?.Eject();
    }

    public void SetBui(BodyScannerConsoleBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(HealthScannerBuiState uiState)
    {
        var hasValidTarget = uiState.Target != NetEntity.Invalid &&
                             _entities.GetEntity(uiState.Target) is { Valid: true };

        EmptyPanel.Visible = !hasValidTarget;
        OccupantPanel.Visible = hasValidTarget;

        if (!hasValidTarget)
            return;

        var target = _entities.GetEntity(uiState.Target);

        PatientLabel.Text = Loc.GetString("rmc-health-analyzer-patient",
            ("name", Identity.Name(target, _entities, _player.LocalEntity)));

        if (!_entities.TryGetComponent(target, out DamageableComponent? damageable))
            return;

        var ent = new Entity<DamageableComponent>(target, damageable);
        AddGroup(ent, BruteLabel, Color.FromHex("#DF3E3E"), "Brute", Loc.GetString("rmc-health-analyzer-brute"));
        AddGroup(ent, BurnLabel, Color.FromHex("#FFB833"), "Burn", Loc.GetString("rmc-health-analyzer-burn"));
        AddGroup(ent, ToxinLabel, Color.FromHex("#25CA4C"), "Toxin", Loc.GetString("rmc-health-analyzer-toxin"));
        AddGroup(ent, OxygenLabel, Color.FromHex("#2E93DE"), "Airloss", Loc.GetString("rmc-health-analyzer-oxygen"));

        if (damageable.DamagePerGroup["Genetic"] > 0)
        {
            CloneBox.Visible = true;
            AddGroup(ent, CloneLabel, Color.FromHex("#02c9c0"), "Genetic", Loc.GetString("rmc-health-analyzer-clone"));
        }
        else
        {
            CloneBox.Visible = false;
        }

        var isPermaDead = false;
        var thresholdsSystem = _entities.System<MobThresholdSystem>();

        if (thresholdsSystem.TryGetIncapThreshold(target, out var threshold))
        {
            var damage = threshold.Value - damageable.TotalDamage;
            HealthBar.MinValue = 0;
            HealthBar.MaxValue = 100;

            if (_mob.IsDead(target) && (_entities.HasComponent<VictimBurstComponent>(target) ||
                _rot.IsRotten(target) || _unrevivable.IsUnrevivable(target) ||
                _entities.HasComponent<RMCDefibrillatorBlockedComponent>(target)))
            {
                isPermaDead = true;
                HealthBar.Value = 100;
                HealthBar.ModulateSelfOverride = Color.Red;
                HealthBarText.Text = Loc.GetString("rmc-health-analyzer-permadead");
            }
            else
            {
                HealthBar.ModulateSelfOverride = null;

                if (damage < 0 && thresholdsSystem.TryGetDeadThreshold(target, out var deadThreshold) &&
                    deadThreshold != threshold)
                    threshold = deadThreshold - threshold;

                var healthValue = damage.Float() / threshold.Value.Float() * 100f;
                HealthBar.Value = healthValue;

                var healthString = MathHelper.CloseTo(healthValue, 100) ? "100%" : $"{healthValue:F2}%";
                HealthBarText.Text = Loc.GetString("rmc-health-analyzer-healthy", ("percent", healthString));
            }
        }

        // Chemical contents
        ChemicalsContainer.DisposeAllChildren();
        var anyChemicals = false;
        var anyUnknown = false;

        if (uiState.Chemicals != null)
        {
            foreach (var reagent in uiState.Chemicals.Contents)
            {
                if (!_prototype.TryIndexReagent(reagent.Reagent.Prototype, out ReagentPrototype? prototype))
                    continue;

                if (prototype.Unknown)
                {
                    anyUnknown = true;
                    continue;
                }

                var text = $"{reagent.Quantity.Float():F1} {prototype.LocalizedName}";
                if (prototype.Overdose != null && reagent.Quantity > prototype.Overdose)
                    text = $"[bold][color=red]{FormattedMessage.EscapeText(text)} OD[/color][/bold]";

                var label = new RichTextLabel();
                label.SetMarkupPermissive(text);
                ChemicalsContainer.AddChild(label);
                anyChemicals = true;
            }
        }

        UnknownReagentsLabel.SetMarkupPermissive(Loc.GetString("rmc-health-analyzer-unknown-reagents"));
        UnknownChemicalsPanel.Visible = anyUnknown;
        ChemicalContentsLabel.Visible = anyChemicals;
        ChemicalContentsSeparator.Visible = anyChemicals;
        ChemicalsContainer.Visible = anyChemicals;

        // Blood
        BloodTypeLabel.Text = "Blood:";
        var bloodMsg = new FormattedMessage();
        bloodMsg.PushColor(Color.FromHex("#25B732"));

        var percentage = uiState.MaxBlood == 0 ? 100 : uiState.Blood.Float() / uiState.MaxBlood.Float() * 100f;
        var percentageString = MathHelper.CloseTo(percentage, 100) ? "100%" : $"{percentage:F1}%";
        bloodMsg.AddText($"{percentageString}, {uiState.Blood}cl");
        bloodMsg.Pop();
        BloodAmountLabel.SetMessage(bloodMsg);

        if (uiState.Bleeding)
            Bleeding.SetMarkup(" [bold][color=#DF3E3E]\\[Bleeding\\][/color][/bold]");
        else
            Bleeding.SetMessage(string.Empty);

        // Temperature
        var temperatureMsg = new FormattedMessage();
        if (uiState.Temperature is { } temperatureKelvin)
        {
            var celsius = TemperatureHelpers.KelvinToCelsius(temperatureKelvin);
            var fahrenheit = TemperatureHelpers.KelvinToFahrenheit(temperatureKelvin);
            temperatureMsg.AddText($"{celsius:F1}ºC ({fahrenheit:F1}ºF)");
        }
        else
        {
            temperatureMsg.AddText("None");
        }

        BodyTemperatureLabel.SetMessage(temperatureMsg);

        // Pulse
        var pulseMsg = new FormattedMessage();
        pulseMsg.AddText(uiState.Pulse);
        PulseLabel.SetMessage(pulseMsg);

        // Medical advice
        AdviceContainer.DisposeAllChildren();
        if (!isPermaDead)
        {
            MedicalAdviceLabel.Visible = true;
            MedicalAdviceSeparator.Visible = true;
            PopulateMedicalAdvice(ent, uiState);
            if (AdviceContainer.ChildCount == 0)
            {
                MedicalAdviceLabel.Visible = false;
                MedicalAdviceSeparator.Visible = false;
            }
        }
        else
        {
            MedicalAdviceLabel.Visible = false;
            MedicalAdviceSeparator.Visible = false;
        }
    }

    private void AddGroup(
        Entity<DamageableComponent> damageable,
        RichTextLabel label,
        Color color,
        ProtoId<DamageGroupPrototype> group,
        string labelStr)
    {
        var msg = new FormattedMessage();
        msg.AddText($"{labelStr}: ");
        msg.PushColor(color);

        var damage = damageable.Comp.DamagePerGroup.GetValueOrDefault(group)
            .Int()
            .ToString(CultureInfo.InvariantCulture);
        if (_wounds.HasUntreated(damageable.Owner, group))
            msg.AddText($"{{{damage}}}");
        else
            msg.AddText($"{damage}");

        msg.Pop();
        label.SetMessage(msg);
    }

    private void PopulateMedicalAdvice(Entity<DamageableComponent> target, HealthScannerBuiState uiState)
    {
        _entities.TryGetComponent(target, out WoundedComponent? wounds);

        var hasBruteWounds = wounds != null && _wounds.HasUntreated((target, wounds), wounds.BruteWoundGroup);
        var hasBurnWounds = wounds != null && _wounds.HasUntreated((target, wounds), wounds.BurnWoundGroup);

        if (_player.LocalEntity is not { } viewer)
            return;

        // Defibrillation related
        if (_mob.IsDead(target))
        {
            var thresholdsSystem = _entities.System<MobThresholdSystem>();

            if (thresholdsSystem.TryGetDeadThreshold(target, out var deadThreshold))
            {
                if (deadThreshold + 30 < target.Comp.Damage.GetTotal() && uiState.Chemicals != null
                    && !uiState.Chemicals.ContainsReagent("CMEpinephrine", null))
                {
                    AddAdvice(Loc.GetString("rmc-health-analyzer-advice-epinedrine"));
                }
                else
                {
                    var defib = string.Empty;
                    if (deadThreshold - 20 <= target.Comp.Damage.GetTotal() &&
                        wounds != null && !hasBruteWounds && !hasBurnWounds)
                        defib = Loc.GetString("rmc-health-analyzer-advice-defib-repeated");
                    else if (deadThreshold > target.Comp.Damage.GetTotal())
                        defib = Loc.GetString("rmc-health-analyzer-advice-defib");

                    if (defib != string.Empty && !_skills.HasAllSkills(viewer, DefibSkill))
                        defib = $"[color=#858585]{defib}[/color]";

                    if (defib != string.Empty)
                        AddAdvice(defib);
                }
            }

            AddAdvice(Loc.GetString("rmc-health-analyzer-advice-cpr"));
        }

        // Surgery related
        if (_entities.TryGetComponent(target, out HolocardStateComponent? holocardComponent) &&
            holocardComponent.HolocardStatus == HolocardStatus.Xeno)
        {
            var larvaSurgery = Loc.GetString("rmc-health-analyzer-advice-larva-surgery");
            if (!_skills.HasAllSkills(viewer, LarvaSurgerySkill))
                larvaSurgery = $"[color=#858585]{larvaSurgery}[/color]";
            AddAdvice(larvaSurgery);
        }

        // Wound related
        if (hasBruteWounds)
            AddAdvice(Loc.GetString("rmc-health-analyzer-advice-brute-wounds"));

        if (hasBurnWounds)
            AddAdvice(Loc.GetString("rmc-health-analyzer-advice-burn-wounds"));

        // Blood related
        if (uiState.Blood < uiState.MaxBlood)
        {
            var bloodPercent = uiState.Blood / uiState.MaxBlood;

            if (bloodPercent < 0.85)
            {
                var bloodpack = Loc.GetString("rmc-health-analyzer-advice-blood-pack");
                if (!_skills.HasAllSkills(viewer, BloodPackSkill))
                    bloodpack = $"[color=#858585]{bloodpack}[/color]";
                AddAdvice(bloodpack);
            }

            if (bloodPercent < 0.9 && uiState.Chemicals != null && !uiState.Chemicals.ContainsReagent("Nutriment", null))
                AddAdvice(Loc.GetString("rmc-health-analyzer-advice-food"));
        }

        // Damage related
        var airloss = target.Comp.DamagePerGroup.GetValueOrDefault("Airloss");
        var brute = target.Comp.DamagePerGroup.GetValueOrDefault("Brute");
        var burn = target.Comp.DamagePerGroup.GetValueOrDefault("Burn");
        var toxin = target.Comp.DamagePerGroup.GetValueOrDefault("Toxin");

        if (airloss > 0 && !_mob.IsDead(target))
        {
            if (airloss > 10 && _mob.IsCritical(target))
                AddAdvice(Loc.GetString("rmc-health-analyzer-advice-cpr-crit"));

            if (airloss > 30 && uiState.Chemicals != null &&
                !uiState.Chemicals.ContainsReagent("CMDexalin", null))
                AddAdvice(Loc.GetString("rmc-health-analyzer-advice-dexalin"));
        }

        if (brute > 30 && uiState.Chemicals != null &&
            !uiState.Chemicals.ContainsReagent("CMBicaridine", null) &&
            !_mob.IsDead(target))
            AddAdvice(Loc.GetString("rmc-health-analyzer-advice-bicaridine"));

        if (burn > 30 && uiState.Chemicals != null &&
            !uiState.Chemicals.ContainsReagent("CMKelotane", null) &&
            !_mob.IsDead(target))
            AddAdvice(Loc.GetString("rmc-health-analyzer-advice-kelotane"));

        if (toxin > 10 && uiState.Chemicals != null &&
            !uiState.Chemicals.ContainsReagent("CMDylovene", null) &&
            !uiState.Chemicals.ContainsReagent("Inaprovaline", null) &&
            !_mob.IsDead(target))
            AddAdvice(Loc.GetString("rmc-health-analyzer-advice-dylovene"));
    }

    private void AddAdvice(string text)
    {
        var label = new RichTextLabel();
        label.SetMarkupPermissive(text);
        AdviceContainer.AddChild(label);
    }
}
