using Content.Shared._RMC14.Medical.Scanner;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;

namespace Content.Shared._RMC14.RMCMedicalRecords;

/// <summary>
///     Entity-bound medical data that needs direct entity access for the body scanner and autodoc.
///     Static medical data (blood type, disabilities, etc.) lives on <see cref="RMCMedicalRecord"/> in the station record set.
/// </summary>
[RegisterComponent, NetworkedComponent, AutoGenerateComponentState]
[Access(typeof(SharedRMCMedicalRecordsSystem))]
public sealed partial class RMCMedicalRecordComponent : Component
{
    /// <summary>
    ///     The time of the last body scan, or null if never scanned.
    /// </summary>
    [DataField, AutoNetworkedField]
    public TimeSpan? LastScanTime;

    /// <summary>
    ///     A snapshot of the body scanner state captured at <see cref="LastScanTime"/>.
    /// </summary>
    [DataField, AutoNetworkedField]
    public HealthScanState? LastScanState;

    /// <summary>
    ///     A list of autodoc procedure entries generated by the body scanner.
    ///     Used by the autodoc's "import scan" to pre-select surgeries.
    /// </summary>
    [DataField, AutoNetworkedField]
    public List<RMCAutodocRecord> AutodocData = [];
}

/// <summary>
///     A single autodoc procedure record entry, identifying procedures detected by the body scanner.
/// </summary>
[Serializable, NetSerializable, DataRecord]
public sealed record RMCAutodocRecord(TimeSpan Time, string Procedure, string Details);
