using Content.Client.Stylesheets;
using Content.Shared._RMC14.Medical.Autodoc;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Medical.Autodoc;

[GenerateTypedNameReferences]
public sealed partial class AutodocConsoleWindow : DefaultWindow
{
    private AutodocConsoleBui? _bui;

    public AutodocConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        StartSurgeryButton.OnPressed += _ => _bui?.StartSurgery();
        ClearButton.OnPressed += _ => _bui?.Clear();
        EjectButton.OnPressed += _ => _bui?.Eject();
        ImportScanButton.OnPressed += _ => _bui?.ImportScan();
        BruteToggleButton.OnPressed += _ => _bui?.ToggleBrute();
        BurnToggleButton.OnPressed += _ => _bui?.ToggleBurn();
        CloseIncisionsToggleButton.OnPressed += _ => _bui?.ToggleCloseIncisions();
        RemoveShrapnelToggleButton.OnPressed += _ => _bui?.ToggleRemoveShrapnel();
        BloodToggleButton.OnPressed += _ => _bui?.ToggleBlood();
        DialysisToggleButton.OnPressed += _ => _bui?.ToggleDialysis();
        ToxinToggleButton.OnPressed += _ => _bui?.ToggleToxin();
        InternalBleedingToggleButton.OnPressed += _ => _bui?.ToggleInternalBleeding();
        BrokenBoneToggleButton.OnPressed += _ => _bui?.ToggleBrokenBone();
        OrganDamageToggleButton.OnPressed += _ => _bui?.ToggleOrganDamage();
        LarvaToggleButton.OnPressed += _ => _bui?.ToggleLarva();
    }

    public void SetBui(AutodocConsoleBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(AutodocBuiState state)
    {
        var hasOccupant = state.Occupant != null;
        EmptyPanel.Visible = !hasOccupant;
        OccupantPanel.Visible = hasOccupant;

        if (!hasOccupant)
            return;

        OccupantNameLabel.Text = state.OccupantName ?? "";

        // Health
        HealthBar.Value = state.Health;
        HealthBar.MaxValue = state.MaxHealth;
        HealthBar.MinValue = 0;
        HealthBarText.Text = $"{state.Health:F0}";

        HealthBar.ForegroundStyleBoxOverride = state.Health switch
        {
            _ when state.Health >= state.MaxHealth * 0.5f => new StyleBoxFlat(Color.FromHex("#408040")),
            >= 0 => new StyleBoxFlat(Color.FromHex("#A0A030")),
            _ => new StyleBoxFlat(Color.FromHex("#A04040"))
        };

        StatusLabel.Text = state.OccupantState switch
        {
            AutodocOccupantMobState.Alive => Loc.GetString("rmc-autodoc-status-alive"),
            AutodocOccupantMobState.Critical => Loc.GetString("rmc-autodoc-status-critical"),
            AutodocOccupantMobState.Dead => Loc.GetString("rmc-autodoc-status-dead"),
            _ => ""
        };
        StatusLabel.Modulate = state.OccupantState switch
        {
            AutodocOccupantMobState.Alive => Color.Lime,
            AutodocOccupantMobState.Critical => Color.Yellow,
            AutodocOccupantMobState.Dead => Color.Red,
            _ => Color.White
        };

        // Blood
        BloodBar.Value = state.BloodPercent;
        BloodBarText.Text = $"{state.BloodPercent:F2}%, {state.BloodLevel}cl";

        BloodBar.ForegroundStyleBoxOverride = state.BloodPercent switch
        {
            >= 90 => new StyleBoxFlat(Color.FromHex("#408040")),
            >= 60 => new StyleBoxFlat(Color.FromHex("#A0A030")),
            _ => new StyleBoxFlat(Color.FromHex("#A04040"))
        };
        PulseLabel.Text = state.Pulse;

        // Damage bars
        UpdateDamageBar(BruteBar, BruteBarText, state.BruteLoss);
        UpdateDamageBar(BurnBar, BurnBarText, state.BurnLoss);
        UpdateDamageBar(ToxinBar, ToxinBarText, state.ToxinLoss);
        UpdateDamageBar(OxygenBar, OxygenBarText, state.OxyLoss);

        // Reagents bar
        ReagentsBar.Value = state.TotalReagents.Float();
        ReagentsBarText.Text = $"{state.TotalReagents:F1}u";
        ReagentsBar.ForegroundStyleBoxOverride = state.TotalReagents.Float() switch
        {
            < 10 => new StyleBoxFlat(Color.FromHex("#408040")),
            < 30 => new StyleBoxFlat(Color.FromHex("#A0A030")),
            _ => new StyleBoxFlat(Color.FromHex("#A04040"))
        };

        // Trauma surgery toggles
        BruteToggleButton.Pressed = state.HealingBrute;
        BurnToggleButton.Pressed = state.HealingBurn;
        CloseIncisionsToggleButton.Pressed = state.CloseIncisions;
        RemoveShrapnelToggleButton.Pressed = state.RemoveShrapnel;

        // Hematology treatment toggles
        BloodToggleButton.Pressed = state.BloodTransfusion;
        DialysisToggleButton.Pressed = state.Filtering;
        ToxinToggleButton.Pressed = state.HealingToxin;

        // Orthopedic surgery toggles
        InternalBleedingToggleButton.Pressed = state.InternalBleeding;
        BrokenBoneToggleButton.Pressed = state.BrokenBone;
        OrganDamageToggleButton.Pressed = state.OrganDamage;
        LarvaToggleButton.Pressed = state.RemoveLarva;

        // Green when at least one surgery is selected
        var anySelected = state.HealingBrute || state.HealingBurn || state.CloseIncisions || state.RemoveShrapnel ||
                          state.BloodTransfusion || state.Filtering || state.HealingToxin ||
                          state.InternalBleeding || state.BrokenBone || state.OrganDamage || state.RemoveLarva;
        if (anySelected)
            StartSurgeryButton.AddStyleClass(StyleNano.StyleClassButtonColorGreen);
        else
            StartSurgeryButton.RemoveStyleClass(StyleNano.StyleClassButtonColorGreen);

        // Disable buttons and turn eject red during surgery
        StartSurgeryButton.Disabled = state.SurgeryInProgress;
        ClearButton.Disabled = state.SurgeryInProgress;
        EjectButton.Modulate = state.SurgeryInProgress ? Color.Red : Color.White;
        ImportScanButton.Disabled = state.SurgeryInProgress;
        BruteToggleButton.Disabled = state.SurgeryInProgress;
        BurnToggleButton.Disabled = state.SurgeryInProgress;
        CloseIncisionsToggleButton.Disabled = state.SurgeryInProgress;
        RemoveShrapnelToggleButton.Disabled = state.SurgeryInProgress;
        BloodToggleButton.Disabled = state.SurgeryInProgress;
        DialysisToggleButton.Disabled = state.SurgeryInProgress;
        ToxinToggleButton.Disabled = state.SurgeryInProgress;
        InternalBleedingToggleButton.Disabled = state.SurgeryInProgress;
        BrokenBoneToggleButton.Disabled = state.SurgeryInProgress;
        OrganDamageToggleButton.Disabled = state.SurgeryInProgress;
        LarvaToggleButton.Disabled = state.SurgeryInProgress;

        // Update button styles based on selection
        UpdateToggleButtonStyle(BruteToggleButton, state.HealingBrute);
        UpdateToggleButtonStyle(BurnToggleButton, state.HealingBurn);
        UpdateToggleButtonStyle(CloseIncisionsToggleButton, state.CloseIncisions);
        UpdateToggleButtonStyle(RemoveShrapnelToggleButton, state.RemoveShrapnel);
        UpdateToggleButtonStyle(BloodToggleButton, state.BloodTransfusion);
        UpdateToggleButtonStyle(DialysisToggleButton, state.Filtering);
        UpdateToggleButtonStyle(ToxinToggleButton, state.HealingToxin);
        UpdateToggleButtonStyle(InternalBleedingToggleButton, state.InternalBleeding);
        UpdateToggleButtonStyle(BrokenBoneToggleButton, state.BrokenBone);
        UpdateToggleButtonStyle(OrganDamageToggleButton, state.OrganDamage);
        UpdateToggleButtonStyle(LarvaToggleButton, state.RemoveLarva);
    }

    private static void UpdateDamageBar(ProgressBar bar, Label label, float damage)
    {
        bar.Value = damage;
        label.Text = damage.ToString("F0");

        bar.ForegroundStyleBoxOverride = damage switch
        {
            < 25 => new StyleBoxFlat(Color.FromHex("#408040")),
            < 50 => new StyleBoxFlat(Color.FromHex("#A0A030")),
            _ => new StyleBoxFlat(Color.FromHex("#A04040"))
        };
    }

    private static void UpdateToggleButtonStyle(Button button, bool active)
    {
        button.Modulate = active ? Color.FromHex("#80FF80") : Color.White;
    }
}
