using Content.Shared._RMC14.Medical.Autodoc;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Medical.Autodoc;

[GenerateTypedNameReferences]
public sealed partial class AutodocConsoleWindow : DefaultWindow
{
    private AutodocConsoleBui? _bui;

    public AutodocConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        BruteToggleButton.OnPressed += _ => _bui?.ToggleBrute();
        BurnToggleButton.OnPressed += _ => _bui?.ToggleBurn();
        ToxinToggleButton.OnPressed += _ => _bui?.ToggleToxin();
        BloodToggleButton.OnPressed += _ => _bui?.ToggleBlood();
        DialysisToggleButton.OnPressed += _ => _bui?.ToggleDialysis();
        LarvaToggleButton.OnPressed += _ => _bui?.ToggleLarva();
        IncisionsToggleButton.OnPressed += _ => _bui?.ToggleIncisions();
        StartSurgeryButton.OnPressed += _ => _bui?.StartSurgery();
        ClearButton.OnPressed += _ => _bui?.Clear();
        EjectButton.OnPressed += _ => _bui?.Eject();
    }

    public void SetBui(AutodocConsoleBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(AutodocBuiState state)
    {
        var hasOccupant = state.Occupant != null;
        EmptyPanel.Visible = !hasOccupant;
        OccupantPanel.Visible = hasOccupant;

        if (!hasOccupant)
            return;

        OccupantNameLabel.Text = state.OccupantName ?? "";

        // Health
        HealthBar.Value = state.Health;
        HealthBar.MaxValue = state.MaxHealth;
        HealthBar.MinValue = 0;
        HealthBarText.Text = $"{state.Health:F0}";

        HealthBar.ForegroundStyleBoxOverride = state.Health switch
        {
            _ when state.Health >= state.MaxHealth * 0.5f => new StyleBoxFlat(Color.FromHex("#408040")),
            >= 0 => new StyleBoxFlat(Color.FromHex("#A0A030")),
            _ => new StyleBoxFlat(Color.FromHex("#A04040"))
        };

        StatusLabel.Text = state.OccupantState switch
        {
            AutodocOccupantMobState.Alive => Loc.GetString("rmc-autodoc-status-alive"),
            AutodocOccupantMobState.Critical => Loc.GetString("rmc-autodoc-status-critical"),
            AutodocOccupantMobState.Dead => Loc.GetString("rmc-autodoc-status-dead"),
            _ => ""
        };
        StatusLabel.Modulate = state.OccupantState switch
        {
            AutodocOccupantMobState.Alive => Color.FromHex("#00FF00"),
            AutodocOccupantMobState.Critical => Color.FromHex("#FFFF00"),
            AutodocOccupantMobState.Dead => Color.FromHex("#FF0000"),
            _ => Color.White
        };

        // Blood level
        BloodSection.Visible = state.HasBlood;
        if (state.HasBlood)
        {
            BloodBar.Value = state.BloodPercent;
            BloodBarText.Text = $"{state.BloodPercent:F2}%, {state.BloodLevel}cl";

            BloodBar.ForegroundStyleBoxOverride = state.BloodPercent switch
            {
                >= 90 => new StyleBoxFlat(Color.FromHex("#408040")),
                >= 60 => new StyleBoxFlat(Color.FromHex("#A0A030")),
                _ => new StyleBoxFlat(Color.FromHex("#A04040"))
            };

            PulseLabel.Text = state.Pulse switch
            {
                0 => Loc.GetString("rmc-pulse-bpm", ("value", 0)),
                >= 250 => Loc.GetString("rmc-pulse-thready-machine"),
                _ => Loc.GetString("rmc-pulse-bpm", ("value", state.Pulse))
            };
        }

        // Damage bars
        UpdateDamageBar(BruteBar, BruteBarText, state.BruteLoss);
        UpdateDamageBar(BurnBar, BurnBarText, state.BurnLoss);
        UpdateDamageBar(ToxinBar, ToxinBarText, state.ToxinLoss);
        UpdateDamageBar(OxygenBar, OxygenBarText, state.OxyLoss);

        // Reagents bar
        ReagentsBar.Value = state.TotalReagents.Float();
        ReagentsBarText.Text = $"{state.TotalReagents:F1}u";
        ReagentsBar.ForegroundStyleBoxOverride = state.TotalReagents.Float() switch
        {
            < 10 => new StyleBoxFlat(Color.FromHex("#408040")),
            < 30 => new StyleBoxFlat(Color.FromHex("#A0A030")),
            _ => new StyleBoxFlat(Color.FromHex("#A04040"))
        };

        // Surgery queue toggles
        BruteToggleButton.Pressed = state.HealingBrute;
        BurnToggleButton.Pressed = state.HealingBurn;
        ToxinToggleButton.Pressed = state.HealingToxin;
        BloodToggleButton.Pressed = state.BloodTransfusion;
        DialysisToggleButton.Pressed = state.Filtering;

        // Surgical procedures toggles
        LarvaToggleButton.Pressed = state.RemoveLarva;
        IncisionsToggleButton.Pressed = state.CloseIncisions;

        // Update availability indicators
        UpdateSurgeryButtonAvailability(LarvaToggleButton, state.HasLarva, state.SurgeryInProgress);
        UpdateSurgeryButtonAvailability(IncisionsToggleButton, state.HasOpenIncisions, state.SurgeryInProgress);

        // Disable buttons during surgery
        BruteToggleButton.Disabled = state.SurgeryInProgress;
        BurnToggleButton.Disabled = state.SurgeryInProgress;
        ToxinToggleButton.Disabled = state.SurgeryInProgress;
        BloodToggleButton.Disabled = state.SurgeryInProgress;
        DialysisToggleButton.Disabled = state.SurgeryInProgress;
        StartSurgeryButton.Disabled = state.SurgeryInProgress;
        ClearButton.Disabled = state.SurgeryInProgress;

        // Surgery status
        SurgeryStatusContainer.Visible = state.SurgeryInProgress;

        // Surgery progress display
        SurgeryProgressContainer.Visible = state.CurrentSurgeryType != AutodocSurgeryType.None;
        if (state.CurrentSurgeryType != AutodocSurgeryType.None)
        {
            SurgeryTypeLabel.Text = state.CurrentSurgeryType switch
            {
                AutodocSurgeryType.LarvaExtraction => Loc.GetString("rmc-autodoc-surgery-larva-progress"),
                AutodocSurgeryType.CloseIncision => Loc.GetString("rmc-autodoc-surgery-incisions-progress"),
                _ => ""
            };
            SurgeryProgressBar.Value = state.SurgeryProgressTime;
            SurgeryProgressText.Text = $"{state.SurgeryProgressTime * 100:F0}%";
            SurgeryProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat(Color.FromHex("#4080C0"));
        }

        // Update button styles based on selection
        UpdateToggleButtonStyle(BruteToggleButton, state.HealingBrute);
        UpdateToggleButtonStyle(BurnToggleButton, state.HealingBurn);
        UpdateToggleButtonStyle(ToxinToggleButton, state.HealingToxin);
        UpdateToggleButtonStyle(BloodToggleButton, state.BloodTransfusion);
        UpdateToggleButtonStyle(DialysisToggleButton, state.Filtering);
        UpdateToggleButtonStyle(LarvaToggleButton, state.RemoveLarva);
        UpdateToggleButtonStyle(IncisionsToggleButton, state.CloseIncisions);
    }

    private static void UpdateDamageBar(ProgressBar bar, Label label, float damage)
    {
        bar.Value = damage;
        label.Text = damage.ToString("F0");

        bar.ForegroundStyleBoxOverride = damage switch
        {
            < 25 => new StyleBoxFlat(Color.FromHex("#408040")),
            < 50 => new StyleBoxFlat(Color.FromHex("#A0A030")),
            _ => new StyleBoxFlat(Color.FromHex("#A04040"))
        };
    }

    private static void UpdateToggleButtonStyle(Button button, bool active)
    {
        button.Modulate = active ? Color.FromHex("#80FF80") : Color.White;
    }

    private static void UpdateSurgeryButtonAvailability(Button button, bool conditionPresent, bool surgeryInProgress)
    {
        button.Disabled = surgeryInProgress;

        // Show visual indicator if condition is present
        if (conditionPresent && !surgeryInProgress)
        {
            button.Modulate = button.Pressed ? Color.FromHex("#80FF80") : Color.FromHex("#FFFF80");
        }
        else if (!conditionPresent)
        {
            button.Modulate = Color.FromHex("#808080");
        }
    }
}
