name: "Labels: Approved (Dummy)"
on:
  pull_request_review:
    types: [submitted]
jobs:
  dummy-workflow:
    # Change the repository name after you've made sure the team name is correct for your fork!
    if: ${{ (github.repository == 'RMC-14/RMC-14') && (github.event.review.state == 'APPROVED') }}
    runs-on: ubuntu-latest
    name: dummy workflow
    steps:
    - name: Explanation
      run: echo "this is a dummy workflow that triggers a workflow_run; it's necessary because otherwise the repo secrets will not be in scope for externally forked pull requests"
